apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ouardini14/ebook_back:v1.0
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URL
              value: "mongodb+srv://Themoby:3fapRU50apc6ond2@cluster0.eopsi5v.mongodb.net/db_books?retryWrites=true&w=majority"